name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  LINUX_APP_NAME: TSLgenerator-linux
  MACOS_APP_NAME: TSLgenerator-macos
  WINDOWS_APP_NAME: TSLgenerator.exe

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build release
      working-directory: ./Linux
      run: make && mv tsl ${{ env.LINUX_APP_NAME }}
    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./Linux/${{ env.LINUX_APP_NAME }}

  build-macos:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: make && mv tsl ${{ env.MACOS_APP_NAME }}
      working-directory: ./MacOSX
      run: make
    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./MacOSX/${{ env.MACOS_APP_NAME }}

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Upgrader
      uses: seanmiddleditch/gha-setup-vsdevenv@master

    - name: Upgrade project
      working-directory: ./Win8
      run: devenv TSLgenerator.sln /Upgrade

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build project
      working-directory: ./Win8
      run: msbuild TSLgenerator.sln /p:configuration=release

    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./Win8/Release/${{ env.WINDOWS_APP_NAME }}
