name: Win8 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Upgrader
      uses: seanmiddleditch/gha-setup-vsdevenv@master

    - name: Upgrade project
      working-directory: ./Win8
      run: devenv TSLgenerator.sln /Upgrade

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build project
      working-directory: ./Win8
      run: msbuild TSLgenerator.sln /p:configuration=debug
