name: Win8 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build project
      uses: microsoft/setup-msbuild@v1.0.1
      working-directory: ./Win8
      run: msbuild TSLgenerator.vcxproj /p:configuration=debug
